### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by ShirasawaSama** [LucunJi/ExtraPlayerRenderer#1]
1. 请求提供 `Fabric1.15.2` 的build
2. 希望可以指定渲染视距以内其他玩家的模型
3. 希望可以通过服务端发送 `channel message` 来控制模型的显示

**Comment by LucunJi** [comment]
不是很懂
> 希望可以通过服务端发送 channel message 来控制模型的显示

可以解释一下用途吗

另外，
> 希望可以指定渲染视距以内其他玩家的模型

是要在旁观者模式附身的时候使用吗
