### ISSUE TITLE
Support for 1.16.4?

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [LucunJi/ExtraPlayerRenderer#12]
我fork了一份源码并修改了版本号，在我的客户端上能够运行，
![image](https://user-images.githubusercontent.com/26178665/103203413-d160ba80-492f-11eb-85d6-3e1db8ba7084.png)

能否支持一个1.16.4的版本？
我看到上游没有对应的branch就没开pull request。

**Comment by LucunJi** [comment]
抱歉久等了，现在已经更新1.16.5版本，应该可以在这里或 CourseForge 下载到。
