### ISSUE TITLE
Crash before client start (Mostlikely incompatibility)

### ISSUE THREAD

**Issue by KamiSami** [LucunJi/ExtraPlayerRenderer#13]
Hi, it seems this mod doesn't like origins mod, i think it was just origins i installed and then the game didn't even boot up before it crashes, now... I am not entirely sure if it is this mod's fault, but if it is i would suggest fix for this issue if possible, considering how popular origins is too... The reason i suspect this mod is because i can run my modpack just fine without this mod in, but whne i get this mod in, it will crash before booting up client, however if i remove origins, that seems to work aswell, so it is mostlikely incompatibility i think? Here is some logs i get before crash: https://pastebin.com/vUyde6fE

If this is any help, let me know, if there is nothing to be done, then feel free to close this issue. Your mod seems interesting as i play sometimes streaming to friends of mine, so i wish i could play these mods in together.

**Comment by LucunJi** [comment]
I did not see anything related to my mod in the logs, but I have the same suspicion. Can you please tell me the modpack's name if I can find the whole pack somewhere, or just send me your mod and configs?

**Comment by KamiSami** [comment]
It is pack i assembled myself, a pretty simple one. I don't know where i should upload configs but i don't think i have adjusted them yet anyway... But the mods i have are following:


adventurez-1.2.6.jar
appleskin-mc1.16-fabric-1.0.11.jar
architectury-1.17.20-fabric.jar
backpackmod-1.16-1.3.1.jar
battletowers-3.3.4-1.16.4.jar
bewitchment-1.16.5-15.jar
can-i-mine-this-block-1.0.2.jar
chatplus-1.0.1.jar
cloth-config-4.11.26-fabric.jar
curios-fabric-0.0.13-1.16.5.jar
DmNHWYLAFF-1.0.0.jar
DungeonsModLite-1.16.5-1.0.5.jar
eternaleats-1.0.4.jar
extraorigins-1.16.5-12.jar
ExtraPlayerRenderer-1.16.5-2.0.1.jar
fabric-api-0.34.6+1.16.jar
fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar
ftb-gui-library-1605.2.1.41-fabric.jar
ftb-ultimine-fabric-1605.2.2-build.4.jar
geckolib-fabric-1.16.5-3.0.39.jar
haema-1.7.0.jar
Hwyla-fabric-1.16.2-1.9.23-79.jar
itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.5.jar
mostructures-1.1.1+mc.1.16.5.jar
mousewheelie-1.7.3+mc1.16.5.jar
Origins-1.16.5-0.7.3.jar
Origins-Classes-1.16.5-1.1.1.jar
Patchouli-1.16.4-51-FABRIC.jar
Pehkui-2.2.0+21w20a.jar
PerspectiveModRedux-0.0.5.jar
prefab-fabric-1.0.4.jar
repurposed_structures-1.16.5-1.11.2-fabric.jar
requiem-1.7.10.jar
requiem-pandemonium-1.7.10.jar
rightclickharvest-1.2.3.jar
RingsOfAscension-1.16.4-1.1.1.jar
RoughlyEnoughItems-5.12.248.jar
RpOrigins-3.0.jar
skinshine-1.1.8.jar
somnus-fabric-0.0.11-1.16.5.jar
torohealth-1.16.4-fabric-4.jar
totemic-overhaul-1.1.5.jar
trinkets-2.6.7.jar
voidz-1.0.1.jar
XaerosWorldMap_1.13.2_Fabric_1.16.5.jar

**Comment by LucunJi** [comment]
I just find some free time and come back to 1.16.5 modding. I tried to solve this bug, and it turns out there is a conflict with FallFlyingLib, a dependency of Origins. You may try upgrading the mods to solve this bug as the latest ExtraPlayerRenderer works fine with the latest FallFlyingLib. Reopen this issue and let me know if the issue still presents after upgrading.

**Comment by LucunJi** [comment]
Some notes for myself: both mods create a `@Invoker` mixin for `Entity#getFlag` method with the same invoker method name `callGetFlag`. If the bug still comes up in the future, several solutions can be found [here](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Resolving-Method-Signature-Conflicts).

The mods for replicating this bug with `geckolib` in a different version: (remove `.gz` extensions and unzip)
[mods.7z.001.gz](https://github.com/LucunJi/ExtraPlayerRenderer/files/10386532/mods.7z.001.gz)
[mods.7z.002.gz](https://github.com/LucunJi/ExtraPlayerRenderer/files/10386533/mods.7z.002.gz)
