### ISSUE TITLE
ExtraPlayerRenderer-1.18-2.1.2  报错打不开

### ISSUE THREAD

**Issue by aoerqileng** [LucunJi/ExtraPlayerRenderer#17]
这个是什么问题呢？
![QQ截图20220106170134](https://user-images.githubusercontent.com/35695457/148357306-a79c2bee-00b1-4b86-9eff-eb6d62ee5cb5.png)
![QQ截图20220106170149](https://user-images.githubusercontent.com/35695457/148357311-57fbadb3-28cc-40b4-9e4f-00174a7a0131.png)

**Comment by LucunJi** [comment]
我用同样的模组测试发现可以正常启动。可以试试看重新下载一遍mod吗？

**Comment by aoerqileng** [comment]
找到问题了 可能是我自己电脑上的JAVA版本的问题 我换了一台电脑可以用了抱歉 打扰到了
