### ISSUE TITLE
F5 mode visual glitch in 1.19.2

### ISSUE THREAD

**Issue by TyIuNnG** [LucunJi/ExtraPlayerRenderer#19]
To clearly demonstrate, it's easier to watch this video https://www.youtube.com/watch?v=-U0HBp-WMBU

Basically, the character seems to be copying the model's pose, making the character move awkwardly in f5 mode.

**Comment by LucunJi** [comment]
fixed. The patch will be included in the next release. Please reopen this issue if the glitch still exists in the upcoming version.
