### ISSUE TITLE
Changing to different player name

### ISSUE THREAD

**Issue by ClassicChad** [LucunJi/ExtraPlayerRenderer#23]
The other day when I put in another players name to use their skin, it worked and showed their skin. Now today when I tried to do it, nothing changes.

**Comment by LucunJi** [comment]
Sounds strange. Did you look into your internet connection? Sometimes an unstable connection may lead to such issue.

**Comment by ClassicChad** [comment]
I go onto a server daily and all my other mods work with no issue.

**Comment by LucunJi** [comment]
This feature currently only applies to players in the same server and visible in the client-side. You might use offline mode with another login name to use other skins.
