### ISSUE TITLE
[1.19.2] version mismatch on 2.2.2

### ISSUE THREAD

**Issue by netcore10** [LucunJi/ExtraPlayerRenderer#24]
![image](https://github.com/LucunJi/ExtraPlayerRenderer/assets/181536/73a55527-43d5-4a0b-b6f2-671be4f29576)

**Comment by netcore10** [comment]
it's tagged as compatable with 1.19.2

**Comment by LucunJi** [comment]
I'm sorry about that, the tagging in Modrinth is now fixed.

If there is some specific reason making you use 1.19.2 instead of 1.19.4, you can reopen this issue or make a new issue.

**Comment by netcore10** [comment]
it's mainly our current mod choices. We're an SMP that's creator based, but with your latest update we kinda lost the 1.19.2 compatability that was there before.

**Comment by LucunJi** [comment]
I've uploaded an extra update for 1.19.2, enjoy your gaming

**Comment by netcore10** [comment]
thank you!
