### ISSUE TITLE
Keeps Resetting

### ISSUE THREAD

**Issue by EyemSoReel** [LucunJi/ExtraPlayerRenderer#38]
Everytime I restart my game, this mod resets and my character is in the bottom left, super huge, it's ugly, I keep having to make it small and put it on the right. 

Please add a save feature or something.

**Comment by PixelTails** [comment]
The config keeps resetting every time i use it.

**Comment by LucunJi** [comment]
It seems you are using `3.0.0-alpha.1` version. I can push a fix quickly, yet please use avoid using the unstable alpha version unless the [sakura-ryoko's malilib fork](https://github.com/sakura-ryoko/malilib/releases) does not work for you.

**Comment by LucunJi** [comment]
See https://github.com/isXander/YetAnotherConfigLib/issues/187 for more details

**Comment by EyemSoReel** [comment]
> See [isXander/YetAnotherConfigLib#187](https://github.com/isXander/YetAnotherConfigLib/issues/187) for more details

Thank you for the efforts, also Sorry for calling the default setting ugly 

Awesome Mod, Excited for it to save in the future.

**Comment by LucunJi** [comment]
Take a look at `3.0.0-alpha.3`. It should work. (but still in alpha -- breaking changes may take place in the future)

**Comment by LucunJi** [comment]
Let's call it a day if this bug stops. My fixing code is nasty but it works, hopefully.

Reopen this issue if the bug still exists.
