### ISSUE TITLE
阴影过暗，F1键无法隐藏模型

### ISSUE THREAD

**Issue by SunBedrock** [LucunJi/ExtraPlayerRenderer#39]
两者均为默认设置，1.21 的 v3.0.0-alpha3 版本明显比 1.20.4 的 v2.3.2 版本的模型更暗

1.21 v3.0.0-alpha3：
![image](https://github.com/LucunJi/ExtraPlayerRenderer/assets/96919723/64f79acf-e424-4855-902c-d274efe7a88c)

1.20.4 v2.3.2：
![image](https://github.com/LucunJi/ExtraPlayerRenderer/assets/96919723/afc14386-fc2c-4d43-b658-94f22ca747d5)

在 1.21 v3.0.0-alpha3 测试过程中，还发现F1键无法隐藏模型，这在 1.20.4 v2.3.2 并不存在

1.21 v3.0.0-alpha3：
![image](https://github.com/LucunJi/ExtraPlayerRenderer/assets/96919723/7bdaafbf-e228-4dca-b755-148b3d9e4f62)

**Comment by LucunJi** [comment]
[1.21-3.0.0-alpha.4](https://github.com/LucunJi/ExtraPlayerRenderer/tree/1.21-3.0.0-alpha.4)
