### ISSUE TITLE
BUG 玩家拿着方块时 出现渲染错误

### ISSUE THREAD

**Issue by jfglzs** [LucunJi/ExtraPlayerRenderer#42]
![QQ_1721737337960](https://github.com/user-attachments/assets/014b4a70-8dbe-42a9-8bc1-013e9ae4c28f)
[latest.log](https://github.com/user-attachments/files/16348698/latest.log)

**Comment by jfglzs** [comment]
版本是最新测试版beta 3.0.0

**Comment by LucunJi** [comment]
可以复现。为什么要关闭？

**Comment by jfglzs** [comment]
> 可以复现。为什么要关闭？

啊 我还以为是我的问题

**Comment by LucunJi** [comment]
fixed in https://github.com/LucunJi/ExtraPlayerRenderer/releases/tag/1.21-3.0.0
