### ISSUE TITLE
游戏无法启动

### ISSUE THREAD

**Issue by xiaoyv404** [LucunJi/ExtraPlayerRenderer#5]
# 环境:
- fabric-loader-0.9.1+build.205-1.15.2
- ExtraPlayerRenderer-1.15.2-0.9
- malilib-fabric-1.15.2-0.10.0-dev.21+arne.3
- fabric-api-0.17.0+build.323
- notenoughcrashes-2.0.0+1.15.1
# bug图，附报错log
![image](https://user-images.githubusercontent.com/63290381/90086728-b0ffdd00-dd4d-11ea-9392-69a6f232b16f.png)
[crash-2020-08-13_09.59.40-server.txt](https://github.com/LucunJi/ExtraPlayerRenderer/files/5066797/crash-2020-08-13_09.59.40-server.txt)
崩溃修复mod生成的：[log](https://gist.githubusercontent.com/natanfudge/079f984ff688aca992a3b68758a9c491/raw/3fcb207ea14132214171968bb3f8e4f42ddeabea/crash.txt)
# 补充:
- 如果没有崩溃修复mod，用启动器正常启动，游戏进程不会有窗口出现，判断为崩溃。

**Comment by xiaoyv404** [comment]
有可能是因为不适配最新的fabric-api？

**Comment by LucunJi** [comment]
是的，适当降低api版本试试看

**Comment by LucunJi** [comment]
已推出最新版本。如果确实得到修复可以把这个issue关了。

**Comment by xiaoyv404** [comment]
好的，我下午去测试一下
