### ISSUE TITLE
[Update Request] Update for compatibility with 1.16.3?

### ISSUE THREAD

**Issue by Abbanon** [LucunJi/ExtraPlayerRenderer#6]
As the title says, I'm requesting an update to allow this mod to work with Minecraft 1.16.3, because right now it does not.
Would this be possible?

**Comment by LucunJi** [comment]
Actually you can change the `fabric.mod.json` file in 1.16.2 mod to make it compatible. I plan to rearrange the config menu when updating to 1.16.3 someday, but still too busy with other stuff to make any updates.

**Comment by LucunJi** [comment]
Sorry for keep you waiting, the mod now supports 1.16.5. You can download it here or in CurseForge.
